export const tarotCards: TarotCard[] = [
  {
    id: 'major-00',
    name: 'The Fool',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 0,
    element: 'Air',
    keywords: ['new beginnings', 'trust', 'adventure', 'freedom'],
    uprightMeaning: 'A new chapter begins. Trust the unknown and take a leap of faith.',
    reversedMeaning: 'Avoiding the leap, fear, or refusing to begin because of insecurity.',
    shortMeaning: 'Fresh start and brave curiosity.',
    symbolism: ['cliff', 'dog', 'backpack', 'sun'],
    numerology: 'Infinite potential and the energy of pure beginnings.'
  },
  {
    id: 'major-01',
    name: 'The Magician',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 1,
    element: 'Air',
    keywords: ['manifestation', 'skill', 'willpower', 'focus'],
    uprightMeaning: 'You already have the tools you need. Focus your intention and act.',
    reversedMeaning: 'Scattered energy, self-doubt, or a talent not being used well.',
    shortMeaning: 'Manifestation and personal power.',
    symbolism: ['wand', 'table', 'tools', 'infinity'],
    numerology: 'The first step into self-creation and conscious action.'
  },
  {
    id: 'major-02',
    name: 'The High Priestess',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 2,
    element: 'Water',
    keywords: ['intuition', 'mystery', 'inner wisdom', 'hidden truth'],
    uprightMeaning: 'Trust the quiet knowing within you. Some answers rise from intuition.',
    reversedMeaning: 'Ignoring intuition, confusion, or disconnected inner guidance.',
    shortMeaning: 'Hidden wisdom and inner knowing.',
    symbolism: ['moon', 'veil', 'water', 'crescent'],
    numerology: 'Balance between conscious thought and subconscious intuition.'
  },
  {
    id: 'major-03',
    name: 'The Empress',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 3,
    element: 'Earth',
    keywords: ['abundance', 'nurture', 'creativity', 'beauty'],
    uprightMeaning: 'Create, nurture, and welcome abundance in a natural, grounded way.',
    reversedMeaning: 'Creative block, neglect, or imbalance between giving and receiving.',
    shortMeaning: 'Growth, beauty, and abundance.',
    symbolism: ['crown', 'wheat', 'heart', 'earth'],
    numerology: 'The energy of flowering, creative expansion, and fertility.'
  },
  {
    id: 'major-04',
    name: 'The Emperor',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 4,
    element: 'Fire',
    keywords: ['structure', 'authority', 'discipline', 'leadership'],
    uprightMeaning: 'Strength comes from structure, boundaries, and wise leadership.',
    reversedMeaning: 'Rigidity, domination, or weak leadership and lack of boundaries.',
    shortMeaning: 'Order, power, and protection.',
    symbolism: ['ram', 'throne', 'scepter', 'stone'],
    numerology: 'Stability and the foundation of disciplined action.'
  },
  {
    id: 'major-05',
    name: 'The Hierophant',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 5,
    element: 'Earth',
    keywords: ['tradition', 'guidance', 'ritual', 'belief'],
    uprightMeaning: 'Seek wisdom from tradition, mentorship, or spiritual structure.',
    reversedMeaning: 'Rigidity, rebellion, or refusing the guidance you truly need.',
    shortMeaning: 'Teaching, ritual, and spiritual guidance.',
    symbolism: ['church', 'staff', 'pillars', 'ceremony'],
    numerology: 'Learning through structure, faith, and shared wisdom.'
  },
  {
    id: 'major-06',
    name: 'The Lovers',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 6,
    element: 'Air',
    keywords: ['love', 'choice', 'values', 'union', 'connection'],
    uprightMeaning: 'A meaningful decision is being made with the heart and the values in mind.',
    reversedMeaning: 'Misalignment, conflict, or choices that don't match your deeper truth.',
    shortMeaning: 'Connection, love, and integrity.',
    symbolism: ['couple', 'angel', 'tree', 'garden'],
    numerology: 'The harmony of relationship, choice, and shared purpose.'
  },
  {
    id: 'major-07',
    name: 'The Chariot',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 7,
    element: 'Fire',
    keywords: ['willpower', 'momentum', 'victory', 'determination'],
    uprightMeaning: 'Move forward with focus and courage; momentum is on your side.',
    reversedMeaning: 'Lack of direction, losing control, or needing to re-commit.',
    shortMeaning: 'Drive and purposeful action.',
    symbolism: ['chariot', 'sphinxes', 'stars', 'road'],
    numerology: 'The force of will, ambition, and disciplined motion.'
  },
  {
    id: 'major-08',
    name: 'Strength',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 8,
    element: 'Fire',
    keywords: ['courage', 'compassion', 'resilience', 'gentleness'],
    uprightMeaning: 'True strength is calm, compassionate, and deeply steady.',
    reversedMeaning: 'Self-doubt, harshness, or fear replacing confidence.',
    shortMeaning: 'Gentle courage and inner resilience.',
    symbolism: ['lion', 'woman', 'flowers', 'sun'],
    numerology: 'Power expressed through patience and compassion.'
  },
  {
    id: 'major-09',
    name: 'The Hermit',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 9,
    element: 'Earth',
    keywords: ['reflection', 'solitude', 'wisdom', 'guidance'],
    uprightMeaning: 'Pause, reflect, and listen for your own inner guidance.',
    reversedMeaning: 'Isolation, withdrawal, or a refusal to seek clarity.',
    shortMeaning: 'Quiet wisdom and personal insight.',
    symbolism: ['lantern', 'mountain', 'staff', 'cloak'],
    numerology: 'The wisdom that comes from contemplation and soul work.'
  },
  {
    id: 'major-10',
    name: 'Wheel of Fortune',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 10,
    element: 'Air',
    keywords: ['change', 'cycles', 'destiny', 'luck', 'turning point'],
    uprightMeaning: 'A major shift is underway; cycles are turning, and timing matters.',
    reversedMeaning: 'Feeling stuck, resisting timing, or fear of change.',
    shortMeaning: 'Turning points and shifting cycles.',
    symbolism: ['wheel', 'sphinx', 'angel', 'tyche'],
    numerology: 'The completion of a cycle and the beginning of another.'
  },
  {
    id: 'major-11',
    name: 'Justice',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 11,
    element: 'Air',
    keywords: ['truth', 'fairness', 'accountability', 'balance'],
    uprightMeaning: 'The truth is becoming clear; choices and consequences are in focus.',
    reversedMeaning: 'Avoidance, bias, or an imbalance that needs correcting.',
    shortMeaning: 'Truth, fairness, and accountability.',
    symbolism: ['scales', 'sword', 'throne', 'figure'],
    numerology: 'Clear seeing and the balancing of truth with consequence.'
  },
  {
    id: 'major-12',
    name: 'The Hanged Man',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 12,
    element: 'Water',
    keywords: ['pause', 'perspective', 'surrender', 'waiting'],
    uprightMeaning: 'A pause is needed to gain a new perspective; let go of control.',
    reversedMeaning: 'Resistance to change, impatience, or refusing to surrender.',
    shortMeaning: 'Pause, surrender, and new perspective.',
    symbolism: ['hanging figure', 'tree', 'circle', 'sacrifice'],
    numerology: 'The wisdom gained through stillness and non-action.'
  },
  {
    id: 'major-13',
    name: 'Death',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 13,
    element: 'Water',
    keywords: ['transformation', 'ending', 'release', 'renewal'],
    uprightMeaning: 'An ending clears the way for a deeper, truer beginning.',
    reversedMeaning: 'Fear of change, clinging to the old, or delayed transformation.',
    shortMeaning: 'Release and transformation.',
    symbolism: ['skeleton', 'horse', 'sun', 'darkness'],
    numerology: 'Deep transformation and the closing of an old cycle.'
  },
  {
    id: 'major-14',
    name: 'Temperance',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 14,
    element: 'Fire',
    keywords: ['healing', 'balance', 'patience', 'moderation'],
    uprightMeaning: 'Blend opposites with patience, and allow healing to happen naturally.',
    reversedMeaning: 'Imbalance, excess, or difficulties finding harmony.',
    shortMeaning: 'Harmony and steady healing.',
    symbolism: ['angel', 'cups', 'sun', 'rainbow'],
    numerology: 'The balancing of extremes into a healthy middle.'
  },
  {
    id: 'major-15',
    name: 'The Devil',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 15,
    element: 'Earth',
    keywords: ['shadow', 'attachment', 'desire', 'bondage'],
    uprightMeaning: 'Notice what is binding or limiting you; freedom begins with awareness.',
    reversedMeaning: 'Breaking unhealthy patterns, confronting the shadow, and reclaiming power.',
    shortMeaning: 'Shadow patterns and material attachment.',
    symbolism: ['devil', 'chains', 'fire', 'horns'],
    numerology: 'The challenge that reveals what must be released.'
  },
  {
    id: 'major-16',
    name: 'The Tower',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 16,
    element: 'Fire',
    keywords: ['upheaval', 'awakening', 'disruption', 'truth'],
    uprightMeaning: 'A sudden shakeup clears away false structures and reveals truth.',
    reversedMeaning: 'Avoiding necessary disruption or dealing with the aftermath.',
    shortMeaning: 'Sudden change and awakening.',
    symbolism: ['tower', 'lightning', 'storm', 'fall'],
    numerology: 'The disruption needed to break illusion and rebuild truth.'
  },
  {
    id: 'major-17',
    name: 'The Star',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 17,
    element: 'Air',
    keywords: ['hope', 'healing', 'inspiration', 'faith'],
    uprightMeaning: 'Hope is returning; trust the path and let healing continue.',
    reversedMeaning: 'Doubt, discouragement, or losing faith in what is still possible.',
    shortMeaning: 'Hope, inspiration, and renewal.',
    symbolism: ['star', 'woman', 'water', 'night sky'],
    numerology: 'The gentle return of hope after turmoil.'
  },
  {
    id: 'major-18',
    name: 'The Moon',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 18,
    element: 'Water',
    keywords: ['dreams', 'uncertainty', 'instinct', 'subconscious'],
    uprightMeaning: 'Not everything is clear yet; trust your instincts while staying grounded.',
    reversedMeaning: 'Clarity emerging, uncertainty dissolving, or fear being faced directly.',
    shortMeaning: 'Mystery, emotion, and intuition.',
    symbolism: ['moon', 'wolf', 'path', 'water'],
    numerology: 'The realm of dreams, emotion, and uncertain truth.'
  },
  {
    id: 'major-19',
    name: 'The Sun',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 19,
    element: 'Fire',
    keywords: ['joy', 'clarity', 'success', 'vitality'],
    uprightMeaning: 'The path is clear and energizing; joy, confidence, and clarity are present.',
    reversedMeaning: 'Low confidence, dimmed joy, or a temporary loss of clarity.',
    shortMeaning: 'Warm success and life-force.',
    symbolism: ['sun', 'child', 'flowers', 'radiance'],
    numerology: 'The radiant energy of vitality, confidence, and truth.'
  },
  {
    id: 'major-20',
    name: 'Judgement',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 20,
    element: 'Fire',
    keywords: ['awakening', 'calling', 'reckoning', 'rebirth'],
    uprightMeaning: 'A calling is sounding; answer it with honesty and courage.',
    reversedMeaning: 'Ignoring a calling, fear of change, or refusing a necessary awakening.',
    shortMeaning: 'Awakening and personal reckoning.',
    symbolism: ['angels', 'trumpet', 'resurrection', 'mountain'],
    numerology: 'The moment of clear waking and the final call to change.'
  },
  {
    id: 'major-21',
    name: 'The World',
    suit: 'Major Arcana',
    arcana: 'major',
    number: 21,
    element: 'Earth',
    keywords: ['completion', 'achievement', 'wholeness', 'fulfillment'],
    uprightMeaning: 'A cycle closes with balance, fulfillment, and the readiness for a new chapter.',
    reversedMeaning: 'Feeling unfinished, blocked completion, or not recognizing success.',
    shortMeaning: 'Completion and integration.',
    symbolism: ['woman', 'wreath', 'world', 'circle'],
    numerology: 'The completion of the full journey and the return to wholeness.'
  },
  {
    id: 'wands-1',
    name: 'Ace of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 1,
    element: 'Fire',
    keywords: ['inspiration', 'spark', 'new venture', 'creative ignition'],
    uprightMeaning: 'A fresh, energizing opportunity is beginning to rise.',
    reversedMeaning: 'Creative block, low motivation, or delayed momentum.',
    shortMeaning: 'New fire and creative potential.',
    symbolism: ['wand', 'flame', 'growth'],
    numerology: 'The seed of passion before action.'
  },
  {
    id: 'wands-2',
    name: 'Two of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 2,
    element: 'Fire',
    keywords: ['planning', 'vision', 'choice', 'future'],
    uprightMeaning: 'The future is opening, and you are choosing the direction of your path.',
    reversedMeaning: 'Indecision, hesitation, or overthinking a future opportunity.',
    shortMeaning: 'Vision and planning.',
    symbolism: ['two wands', 'horizon'],
    numerology: 'The tension between possibility and decision.'
  },
  {
    id: 'wands-3',
    name: 'Three of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 3,
    element: 'Fire',
    keywords: ['expansion', 'foresight', 'progress', 'opportunity'],
    uprightMeaning: 'The groundwork has been laid and opportunities are now opening beyond the current horizon.',
    reversedMeaning: 'Frustration, impatience, or a lack of trust in timing.',
    shortMeaning: 'Vision expanding outward.',
    symbolism: ['three wands', 'sea', 'horizon'],
    numerology: 'Momentum building through patience and foresight.'
  },
  {
    id: 'wands-4',
    name: 'Four of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 4,
    element: 'Fire',
    keywords: ['celebration', 'home', 'stability', 'joy'],
    uprightMeaning: 'A strong foundation brings justification to celebrate what has been built.',
    reversedMeaning: 'Disruption, instability, or trouble enjoying success.',
    shortMeaning: 'Celebration and secure foundations.',
    symbolism: ['home', 'flowers', 'wands'],
    numerology: 'The comfort of a stable and cherished chapter.'
  },
  {
    id: 'wands-5',
    name: 'Five of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 5,
    element: 'Fire',
    keywords: ['competition', 'challenge', 'rivalry', 'conflict'],
    uprightMeaning: 'Healthy conflict may be active, but it can sharpen skills and reveal strengths.',
    reversedMeaning: 'Avoidance of conflict or a struggle that has become exhausting.',
    shortMeaning: 'Challenge and competitive motion.',
    symbolism: ['wands', 'battle', 'tension'],
    numerology: 'Testing through friction and resistance.'
  },
  {
    id: 'wands-6',
    name: 'Six of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 6,
    element: 'Fire',
    keywords: ['success', 'recognition', 'victory', 'confidence'],
    uprightMeaning: 'Your efforts are being recognized, and success is becoming visible.',
    reversedMeaning: 'Self-doubt, insecurity, or being unready to receive recognition.',
    shortMeaning: 'Victory and public recognition.',
    symbolism: ['horse', 'flag', 'crowd'],
    numerology: 'The reward of effort becoming visible.'
  },
  {
    id: 'wands-7',
    name: 'Seven of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 7,
    element: 'Fire',
    keywords: ['defense', 'persistence', 'boundaries', 'resilience'],
    uprightMeaning: 'Protect what matters, and stand your ground without losing your purpose.',
    reversedMeaning: 'Exhaustion, pressure, or giving up when you still need to defend your position.',
    shortMeaning: 'Defensiveness and perseverance.',
    symbolism: ['wands', 'hill', 'guard'],
    numerology: 'Holding the line through challenge and pressure.'
  },
  {
    id: 'wands-8',
    name: 'Eight of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 8,
    element: 'Fire',
    keywords: ['speed', 'momentum', 'communication', 'arrival'],
    uprightMeaning: 'Things move quickly now; messages, opportunities, and action are all accelerating.',
    reversedMeaning: 'Delayed messages, blocked momentum, or communication breakdown.',
    shortMeaning: 'Swift movement and forward motion.',
    symbolism: ['wands', 'air', 'speed'],
    numerology: 'Rapid movement and immediate results.'
  },
  {
    id: 'wands-9',
    name: 'Nine of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 9,
    element: 'Fire',
    keywords: ['endurance', 'resilience', 'protection', 'last push'],
    uprightMeaning: 'You’ve already survived much; keep your guard, but trust your strength.',
    reversedMeaning: 'Exhaustion, fatigue, or fear that the effort is not worth it.',
    shortMeaning: 'Endurance and final effort.',
    symbolism: ['wands', 'fortified stance'],
    numerology: 'Close to completion but still needing courage.'
  },
  {
    id: 'wands-10',
    name: 'Ten of Wands',
    suit: 'Wands',
    arcana: 'minor',
    number: 10,
    element: 'Fire',
    keywords: ['burden', 'responsibility', 'pressure', 'completion'],
    uprightMeaning: 'A heavy load may be present, but it can also be a sign of meaningful progress.',
    reversedMeaning: 'Overwhelm, release, or the need to let go of unnecessary responsibility.',
    shortMeaning: 'Responsibility and the weight of effort.',
    symbolism: ['burden', 'wands', 'road'],
    numerology: 'The culmination of effort and the cost of success.'
  },
  {
    id: 'cups-1',
    name: 'Ace of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 1,
    element: 'Water',
    keywords: ['love', 'emotion', 'healing', 'intuition'],
    uprightMeaning: 'An emotional opening or heartfelt beginning is arriving.',
    reversedMeaning: 'Emotional block, fear of vulnerability, or difficulty receiving love.',
    shortMeaning: 'Emotional beginning and healing.',
    symbolism: ['cup', 'water', 'dove'],
    numerology: 'A fresh well of feeling and spiritual receptivity.'
  },
  {
    id: 'cups-2',
    name: 'Two of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 2,
    element: 'Water',
    keywords: ['partnership', 'mutuality', 'connection', 'romance'],
    uprightMeaning: 'Connection is mutual and meaningful; emotional reciprocity is strong.',
    reversedMeaning: 'Uneven energy, unresolved tension, or disconnection in a bond.',
    shortMeaning: 'Partnership and emotional reciprocity.',
    symbolism: ['two cups', 'shared offering'],
    numerology: 'The balance of feeling and mutual exchange.'
  },
  {
    id: 'cups-3',
    name: 'Three of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 3,
    element: 'Water',
    keywords: ['celebration', 'friendship', 'joy', 'community'],
    uprightMeaning: 'Warmth, celebration, and connection are bringing nourishment and joy.',
    reversedMeaning: 'Exclusion, emotional distance, or not making time for support.',
    shortMeaning: 'Social joy and emotional sharing.',
    symbolism: ['three cups', 'celebration'],
    numerology: 'A joyful chapter built through connection.'
  },
  {
    id: 'cups-4',
    name: 'Four of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 4,
    element: 'Water',
    keywords: ['apathy', 'contemplation', 'discontent', 'reflection'],
    uprightMeaning: 'You may be too focused on what is missing to notice what is already there.',
    reversedMeaning: 'A shift in perspective, re-engagement, or emotional recognition.',
    shortMeaning: 'Emotional pause and evaluation.',
    symbolism: ['four cups', 'tree'],
    numerology: 'The pause before choosing what truly matters.'
  },
  {
    id: 'cups-5',
    name: 'Five of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 5,
    element: 'Water',
    keywords: ['loss', 'grief', 'disappointment', 'healing'],
    uprightMeaning: 'Grief or disappointment is active, but healing is still possible.',
    reversedMeaning: 'Acceptance, recovery, and a returning sense of hope.',
    shortMeaning: 'Loss and emotional recovery.',
    symbolism: ['five cups', 'mourning'],
    numerology: 'Feeling the loss fully before moving onward.'
  },
  {
    id: 'cups-6',
    name: 'Six of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 6,
    element: 'Water',
    keywords: ['nostalgia', 'healing', 'innocence', 'memory'],
    uprightMeaning: 'There is gentleness, remembrance, and a healing connection to the past.',
    reversedMeaning: 'Replaying old emotional dynamics or struggling to let go.',
    shortMeaning: 'Nostalgia and emotional healing.',
    symbolism: ['six cups', 'childhood'],
    numerology: 'A return that offers perspective and comfort.'
  },
  {
    id: 'cups-7',
    name: 'Seven of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 7,
    element: 'Water',
    keywords: ['fantasy', 'choices', 'illusion', 'dreams'],
    uprightMeaning: 'Many possibilities are appearing, but not all are grounded in reality.',
    reversedMeaning: 'Clarity, focus, and choosing what is truly meaningful.',
    shortMeaning: 'Dreams and emotionally confusing options.',
    symbolism: ['seven cups', 'visions'],
    numerology: 'A creative but potentially unclear threshold.'
  },
  {
    id: 'cups-8',
    name: 'Eight of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 8,
    element: 'Water',
    keywords: ['walking away', 'journey', 'search', 'release'],
    uprightMeaning: 'A necessary emotional journey requires leaving behind what no longer fits.',
    reversedMeaning: 'Reluctance to leave, or fear of the unknown after a meaningful goodbye.',
    shortMeaning: 'Leaving behind what no longer nourishes you.',
    symbolism: ['cups', 'mountain path'],
    numerology: 'The movement toward meaning, even when it costs comfort.'
  },
  {
    id: 'cups-9',
    name: 'Nine of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 9,
    element: 'Water',
    keywords: ['satisfaction', 'contentment', 'gratitude', 'wish fulfillment'],
    uprightMeaning: 'Emotional fulfillment is present; gratitude is a powerful current here.',
    reversedMeaning: 'Feeling emotionally unfulfilled even when outwardly comfortable.',
    shortMeaning: 'Contentment and wish fulfillment.',
    symbolism: ['nine cups', 'comfort'],
    numerology: 'A feeling of emotional abundance and complete satisfaction.'
  },
  {
    id: 'cups-10',
    name: 'Ten of Cups',
    suit: 'Cups',
    arcana: 'minor',
    number: 10,
    element: 'Water',
    keywords: ['family', 'harmony', 'home', 'belonging'],
    uprightMeaning: 'Emotional fulfillment, belonging, and shared joy are in focus.',
    reversedMeaning: 'Family tension, disconnection, or insecurity around belonging.',
    shortMeaning: 'Home, harmony, and emotional completion.',
    symbolism: ['family', 'home', 'rainbow'],
    numerology: 'The deep completion of emotional security.'
  },
  {
    id: 'swords-1',
    name: 'Ace of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 1,
    element: 'Air',
    keywords: ['clarity', 'truth', 'breakthrough', 'mental focus'],
    uprightMeaning: 'A clear truth or breakthrough arrives and cuts through confusion.',
    reversedMeaning: 'Muddled thinking, difficulty seeing the truth, or delayed clarity.',
    shortMeaning: 'Truth and decisive perception.',
    symbolism: ['sword', 'clouds', 'crown'],
    numerology: 'A sharp, clear beginning in thought and decision.'
  },
  {
    id: 'swords-2',
    name: 'Two of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 2,
    element: 'Air',
    keywords: ['indecision', 'balance', 'choice', 'pause'],
    uprightMeaning: 'A decision is near, but a pause is needed before the next step.',
    reversedMeaning: 'A decision is finally made, though it may come with difficulty.',
    shortMeaning: 'Careful choice and mental balance.',
    symbolism: ['two swords', 'blindfold'],
    numerology: 'The tension between two truths requiring balance.'
  },
  {
    id: 'swords-3',
    name: 'Three of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 3,
    element: 'Air',
    keywords: ['heartbreak', 'truth', 'grief', 'release'],
    uprightMeaning: 'Pain or heartbreak reveals the truth and opens a path toward healing.',
    reversedMeaning: 'Recovery, acceptance, or the release of emotional pain.',
    shortMeaning: 'Truth through pain and emotional release.',
    symbolism: ['three swords', 'heart'],
    numerology: 'The painful honesty that clears the way forward.'
  },
  {
    id: 'swords-4',
    name: 'Four of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 4,
    element: 'Air',
    keywords: ['rest', 'recovery', 'pause', 'retreat'],
    uprightMeaning: 'A period of rest is needed for clarity and healing to return.',
    reversedMeaning: 'Returning to activity too soon or struggling to rest.',
    shortMeaning: 'Recovery and mental retreat.',
    symbolism: ['four swords', 'chapel'],
    numerology: 'The necessary rest before the next movement.'
  },
  {
    id: 'swords-5',
    name: 'Five of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 5,
    element: 'Air',
    keywords: ['conflict', 'ego', 'stress', 'power struggle'],
    uprightMeaning: 'A conflict is active; be careful not to let ego or win-at-all-costs energy dominate.',
    reversedMeaning: 'Repairing damage, stepping away from power struggle, and choosing peace.',
    shortMeaning: 'Conflict and ego tension.',
    symbolism: ['five swords', 'battle'],
    numerology: 'The challenge that exposes insecurity and control issues.'
  },
  {
    id: 'swords-6',
    name: 'Six of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 6,
    element: 'Air',
    keywords: ['transition', 'healing', 'travel', 'change'],
    uprightMeaning: 'Movement away from stress is underway; calm is beginning to return.',
    reversedMeaning: 'Difficulty moving forward or carrying old mental baggage.',
    shortMeaning: 'Transition and calmer movement.',
    symbolism: ['boat', 'water', 'passage'],
    numerology: 'The release of tension and the beginning of calmer travel.'
  },
  {
    id: 'swords-7',
    name: 'Seven of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 7,
    element: 'Air',
    keywords: ['strategy', 'stealth', 'risk', 'hidden motives'],
    uprightMeaning: 'A careful strategy may be required; pay attention to what is being left unsaid.',
    reversedMeaning: 'Hidden truths are becoming visible and strategic behavior may need correction.',
    shortMeaning: 'Strategy, secrecy, and vigilance.',
    symbolism: ['seven swords', 'night'],
    numerology: 'A mind working quietly and selectively.'
  },
  {
    id: 'swords-8',
    name: 'Eight of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 8,
    element: 'Air',
    keywords: ['restriction', 'mental trap', 'fear', 'limitation'],
    uprightMeaning: 'The mind may be constraining you through fear or a too-small perspective.',
    reversedMeaning: 'Breaking a mental trap and reclaiming clarity and freedom.',
    shortMeaning: 'Self-imposed limitation and fear.',
    symbolism: ['bound figure', 'swords'],
    numerology: 'The trap created by thought and belief.'
  },
  {
    id: 'swords-9',
    name: 'Nine of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 9,
    element: 'Air',
    keywords: ['anxiety', 'worry', 'fear', 'night thoughts'],
    uprightMeaning: 'Fear and worry are heavy, especially in the quiet of the mind.',
    reversedMeaning: 'Relief from worry and a stronger ability to face what was feared.',
    shortMeaning: 'Anxiety and mental agitation.',
    symbolism: ['nine swords', 'bed'],
    numerology: 'The weight of worry that requests honest naming.'
  },
  {
    id: 'swords-10',
    name: 'Ten of Swords',
    suit: 'Swords',
    arcana: 'minor',
    number: 10,
    element: 'Air',
    keywords: ['ending', 'betrayal', 'release', 'closure'],
    uprightMeaning: 'A painful ending is occurring, but it is also the start of a new cycle.',
    reversedMeaning: 'Recovery, healing, or the release of a painful chapter.',
    shortMeaning: 'Painful ending and renewal.',
    symbolism: ['ten swords', 'darkness'],
    numerology: 'Completion in its hardest form, before the next beginning.'
  },
  {
    id: 'pentacles-1',
    name: 'Ace of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 1,
    element: 'Earth',
    keywords: ['opportunity', 'stability', 'grounding', 'growth'],
    uprightMeaning: 'A practical opportunity has emerged and is ready to be cultivated.',
    reversedMeaning: 'Missed opportunity or a need to invest more consistently.',
    shortMeaning: 'Practical opportunity and grounded growth.',
    symbolism: ['pentacle', 'garden'],
    numerology: 'The root of material opportunity and patient development.'
  },
  {
    id: 'pentacles-2',
    name: 'Two of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 2,
    element: 'Earth',
    keywords: ['balance', 'adaptation', 'juggling', 'flexibility'],
    uprightMeaning: 'You are balancing competing demands with flexibility and steadiness.',
    reversedMeaning: 'Disorganization, overload, or difficulty keeping things in balance.',
    shortMeaning: 'Balancing responsibilities and resources.',
    symbolism: ['two pentacles', 'balancing'],
    numerology: 'The balancing act of work, care, and resources.'
  },
  {
    id: 'pentacles-3',
    name: 'Three of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 3,
    element: 'Earth',
    keywords: ['teamwork', 'craft', 'skill', 'collaboration'],
    uprightMeaning: 'Skill and cooperation are creating meaningful progress and tangible results.',
    reversedMeaning: 'Poor collaboration, lack of focus, or a need to sharpen your craft.',
    shortMeaning: 'Craftsmanship and team effort.',
    symbolism: ['three pentacles', 'building'],
    numerology: 'The building phase where skill and effort mature.'
  },
  {
    id: 'pentacles-4',
    name: 'Four of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 4,
    element: 'Earth',
    keywords: ['security', 'control', 'resource protection', 'stability'],
    uprightMeaning: 'Security matters now; you are protecting what supports your wellbeing.',
    reversedMeaning: 'Overcontrol, fear of loss, or difficulty releasing attachment to resources.',
    shortMeaning: 'Control and material stability.',
    symbolism: ['four pentacles', 'guarding'],
    numerology: 'A stable holding pattern around what matters.'
  },
  {
    id: 'pentacles-5',
    name: 'Five of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 5,
    element: 'Earth',
    keywords: ['hardship', 'support', 'struggle', 'recovery'],
    uprightMeaning: 'There may be hardship, but support is still available if you ask for it.',
    reversedMeaning: 'Recovery, relief, or a willingness to accept help.',
    shortMeaning: 'Hardship and the need for support.',
    symbolism: ['five pentacles', 'struggle'],
    numerology: 'The tension of scarcity before renewal.'
  },
  {
    id: 'pentacles-6',
    name: 'Six of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 6,
    element: 'Earth',
    keywords: ['generosity', 'fairness', 'giving', 'receiving'],
    uprightMeaning: 'There is a healthy exchange of giving and receiving; balance is important.',
    reversedMeaning: 'Imbalance, one-sidedness, or difficulty accepting support.',
    shortMeaning: 'Reciprocity and practical fairness.',
    symbolism: ['six pentacles', 'balance'],
    numerology: 'A moment of equilibrium and mutual support.'
  },
  {
    id: 'pentacles-7',
    name: 'Seven of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 7,
    element: 'Earth',
    keywords: ['patience', 'assessment', 'growth', 'watching'],
    uprightMeaning: 'Progress is happening, but patience is still required before judging the outcome.',
    reversedMeaning: 'Impatience, doubt, or premature judgment about what is growing.',
    shortMeaning: 'Patience and long-term growth.',
    symbolism: ['seven pentacles', 'garden'],
    numerology: 'The phase where the results are forming in quiet ways.'
  },
  {
    id: 'pentacles-8',
    name: 'Eight of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 8,
    element: 'Earth',
    keywords: ['work', 'craft', 'diligence', 'mastery'],
    uprightMeaning: 'Focused effort and practice are building real mastery and usefulness.',
    reversedMeaning: 'Burnout, poor focus, or perfectionism that blocks progress.',
    shortMeaning: 'Mastery through disciplined effort.',
    symbolism: ['eight pentacles', 'craft'],
    numerology: 'The height of effort becoming skill.'
  },
  {
    id: 'pentacles-9',
    name: 'Nine of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 9,
    element: 'Earth',
    keywords: ['abundance', 'self-sufficiency', 'reward', 'luxury'],
    uprightMeaning: 'You are enjoying the rewards of effort, self-trust, and secure foundations.',
    reversedMeaning: 'Anxiety about resources, dependence, or inability to enjoy success.',
    shortMeaning: 'Refined abundance and independence.',
    symbolism: ['nine pentacles', 'garden'],
    numerology: 'The fruit of effort becoming a rich and sustainable life.'
  },
  {
    id: 'pentacles-10',
    name: 'Ten of Pentacles',
    suit: 'Pentacles',
    arcana: 'minor',
    number: 10,
    element: 'Earth',
    keywords: ['legacy', 'wealth', 'family', 'long-term security'],
    uprightMeaning: 'A strong foundation is in place, and what is being built has long-term value.',
    reversedMeaning: 'Instability, family tension, or insecurity around lasting security.',
    shortMeaning: 'Legacy, wealth, and long-term stability.',
    symbolism: ['ten pentacles', 'family'],
    numerology: 'The full mature expression of grounded success.'
  }
];

export const tarotDeck = tarotCards;

export const tarotLessons = {
  foundations: {
    title: 'Tarot Foundations',
    points: [
      'The deck is divided into the Major Arcana and Minor Arcana.',
      'Major Arcana cards point to life themes and large turning points.',
      'Minor Arcana cards reflect everyday situations, emotions, and practical life.',
      'The four suits are Wands, Cups, Swords, and Pentacles.'
    ]
  },
  suits: {
    title: 'Suit Meanings',
    points: [
      'Wands = creativity, motivation, action, and passion.',
      'Cups = emotion, intuition, relationships, and healing.',
      'Swords = thoughts, truth, communication, and challenge.',
      'Pentacles = work, money, stability, and grounded growth.'
    ]
  },
  numerology: {
    title: 'Numerology Basics',
    points: [
      'Ace = new beginning',
      'Two = balance and partnership',
      'Three = growth and expression',
      'Four = stability and structure',
      'Five = change and challenge',
      'Six = harmony and responsibility',
      'Seven = reflection and insight',
      'Eight = mastery and momentum',
      'Nine = completion and wisdom',
      'Ten = culmination and completion'
    ]
  }
};

export const tarotQuiz: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Which suit is associated with emotions and relationships?',
    options: ['Wands', 'Cups', 'Swords', 'Pentacles'],
    answer: 'Cups'
  },
  {
    id: 'q2',
    question: 'Which card is associated with new beginnings?',
    options: ['The World', 'The Fool', 'The Chariot', 'The Hermit'],
    answer: 'The Fool'
  },
  {
    id: 'q3',
    question: 'Which suit is linked to practical and material life?',
    options: ['Wands', 'Cups', 'Swords', 'Pentacles'],
    answer: 'Pentacles'
  }
];
